version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: phs
      POSTGRES_USER: phs
      POSTGRES_PASSWORD: phs
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    working_dir: /app
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      DJANGO_DEBUG: "1"
      DJANGO_SECRET_KEY: "dev-secret-change-me"
      DATABASE_URL: "postgres://phs:phs@db:5432/phs"
      REDIS_URL: "redis://redis:6379/1"
      CORS_ALLOWED_ORIGINS: "http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000"
      ALLOWED_HOSTS: "*"
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

volumes:
  pgdata:
